name: dbt Pipeline

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 11 10 * *'  #10th of each month at 8 AM Brasília time
  workflow_dispatch:

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Load environment variables
        run: |
          echo "${{ secrets.DBT_ENV }}" > .env
          export $(cat .env | xargs)
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV

      - name: Install dbt
        run: |
          pip install dbt-athena-community

      - name: Install dbt packages
        run: dbt deps

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          der_sp:
            target: dev
            outputs:
              dev:
                type: athena
                s3_staging_dir: s3://smm-packt-serverless-analytics/results/dbt/
                s3_data_dir: s3://smm-packt-serverless-analytics/dbt-data/
                s3_data_naming: schema_table
                region_name: ${{ env.AWS_REGION }}
                database: awsdatacatalog
                schema: dbt_der
                aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
                aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                threads: 4
                num_retries: 1
              seed:
                type: athena
                s3_staging_dir: s3://smm-packt-serverless-analytics/results/dbt/
                s3_data_dir: s3://der-sp-bucket/raw/
                s3_data_naming: table
                region_name: ${{ env.AWS_REGION }}
                database: awsdatacatalog
                schema: dbt_der
                aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
                aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                threads: 1
                num_retries: 0
              snapshot:
                type: athena
                s3_staging_dir: s3://smm-packt-serverless-analytics/results/dbt/
                s3_data_dir: s3://der-sp-bucket/snapshot/
                s3_data_naming: schema_table
                region_name: ${{ env.AWS_REGION }}
                database: awsdatacatalog
                schema: dbt_der
                aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
                aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                threads: 1
                num_retries: 0
          EOF

      - name: Run dbt seed
        run: dbt seed --target seed

      - name: Run dbt build
        run: dbt build --target dev

      - name: Run dbt snapshot
        run: dbt snapshot --target snapshot

      - name: Generate dbt docs
        run: dbt docs generate --target dev

      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-artifacts
          path: target/


      - name: Deploy dbt docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./target
